language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

matrix:
  include:
    - python: '3.6'
      env: TOXENV=flake8
    - python: '3.6'
      env: TOXENV=isort

install:
  - pip install coverage coveralls tox tox-travis

script:
  - tox

after_success:
  - coverage combine
  - coveralls
